# Generated by Django 2.2.5 on 2020-01-22 23:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('coins', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Litecoin', 'Litecoin'), ('Ripple', 'Ripple'), ('Ethereum', 'Ethereum'), ('Dogecoin', 'Dogecoin')], max_length=30)),
            ],
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
    ]
